# Generated by Django 3.0.7 on 2020-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.ImageField(default='./images/userdefaultimg.png', null=True, upload_to='', verbose_name='카페아이콘'),
        ),
    ]
