# Generated by Django 3.0.6 on 2020-06-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='Explain',
            field=models.TextField(max_length=1000, verbose_name='카페설명'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='title',
            field=models.CharField(max_length=100, verbose_name='카페명'),
        ),
    ]
