# Generated by Django 3.0.7 on 2020-06-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0002_auto_20200615_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.ImageField(default='SSGGA/static/img/userimg.png', null=True, upload_to='', verbose_name='카페 아이콘'),
        ),
    ]
