# Generated by Django 3.0.7 on 2020-06-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0011_auto_20200615_1234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cafe',
            old_name='image',
            new_name='cafe_icon',
        ),
    ]
