# Generated by Django 3.0.6 on 2020-06-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(null=True, verbose_name='생년월일'),
        ),
    ]
