# Generated by Django 3.0.6 on 2020-06-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200602_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=20, null=True, verbose_name='닉네임'),
        ),
    ]
