# Generated by Django 3.0.7 on 2020-06-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20200602_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='./static/img/defaultimg.png', null=True, upload_to='', verbose_name='(선택) 프로필사진'),
        ),
    ]
