# Generated by Django 3.0.7 on 2020-06-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200607_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='./images/userdefaultimg.png', null=True, upload_to='', verbose_name='(선택) 프로필사진'),
        ),
    ]
