# Generated by Django 3.0.7 on 2020-06-15 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_board_cafe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='cafe',
        ),
    ]
