# Generated by Django 3.0.7 on 2020-06-15 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cafeapp', '0012_auto_20200615_1253'),
        ('board', '0003_remove_board_cafe'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='cafe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cafeapp.Cafe'),
        ),
    ]
