# Generated by Django 3.0.7 on 2020-06-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_board_cafe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
