# Generated by Django 3.0.6 on 2020-06-03 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafeapp', '0002_auto_20200603_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makenewcafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cafeapp.Cafe')),
            ],
        ),
    ]
