# Generated by Django 3.0.6 on 2020-06-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='makenewcafe',
            old_name='ttl',
            new_name='Cafe',
        ),
    ]
