# Generated by Django 3.0.6 on 2020-06-03 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200603_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Makenewcafe',
        ),
    ]
