# Generated by Django 3.0.6 on 2020-06-06 18:00

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_deco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyinfoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', imagekit.models.fields.ProcessedImageField(default='user_default_img.png', upload_to='myinfo_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/'),
        ),
    ]
