<<<<<<< HEAD
# Generated by Django 3.0.6 on 2020-06-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_deco', '0002_auto_20200607_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyinfoImage',
        ),
    ]
=======
# Generated by Django 3.0.7 on 2020-06-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_deco', '0002_auto_20200607_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyinfoImage',
        ),
    ]
>>>>>>> 16fbaf0850e2dd12b12a57daf4db2037cdbf4d8d
