# Generated by Django 3.0.7 on 2020-06-07 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_deco', '0002_auto_20200607_0300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyinfoImage',
        ),
    ]
